inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.2.2
  SuggestExtensions: false
  Exclude:
  - 'db/schema.rb'
  - 'config/**/*'
  - 'bin/**/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120
